<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="vawt_1" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->



  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find vawt_1)/urdf/vawt_1.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find vawt_1)/urdf/materials.xacro" />

  <xacro:include filename="$(find vawt_1)/urdf/macros/box_link.xacro" />
  <xacro:include filename="$(find vawt_1)/urdf/macros/cylinder_link.xacro" />
  <xacro:include filename="$(find vawt_1)/urdf/macros/blade_w_struts.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base"/>
  </joint>

  <!-- Base Link -->
  <xacro:property name="base_width" value="2" /> <!-- x  -->
  <xacro:property name="base_height" value="2" /> <!-- y  -->
  <xacro:property name="base_depth" value="0.1" /> <!-- z -->

  <xacro:box_link link_name="base" width="${base_width}" height="${base_height}" depth="${base_depth}"
    xyz="0 0 ${base_depth/2}" rpy="0 0 0" material="orange" mass="${mass}"/>

  <joint name="main_shaft_joint" type="continuous">
    <parent link="base"/>
    <child link="main_shaft"/>
    <origin xyz="0 0 ${base_depth}"/>
    <axis xyz="0 0 1" />
    <dynamics damping="50" friction="1"/>
  </joint>

  <!-- main_shaft Link -->
  <xacro:property name="ms_radius" value="0.1" /> <!-- r  -->
  <xacro:property name="ms_length" value="2" /> <!-- l  -->
  <xacro:property name="shaft_name" value="main_shaft" /> <!-- l  -->

  <xacro:cylinder_link link_name="${shaft_name}" length="${ms_length}" radius="${ms_radius}"
    xyz="0 0 ${ms_length/2}" rpy="0 0 0" material="blue" mass="${mass}"/>

  <!-- blade_1 link -->
  <xacro:blade_w_struts blade_name="blade_1" parent_name="${shaft_name}" shaft_radius="${ms_radius}"
    shaft_length="${ms_length}" blade_offset="0"/>

  <xacro:blade_w_struts blade_name="blade_2" parent_name="${shaft_name}" shaft_radius="${ms_radius}"
    shaft_length="${ms_length}" blade_offset="${pi}"/>


</robot>
