# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.03

# Settings for ros_control hardware interface
hardware_interface:
   joints:
      - blade_1_joint
      - blade_2_joint
      - main_shaft_joint
   sim_control_mode: 0 # 0: position, 1: velocity

# Publish all joint states ----------------------------------
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Individual Position Controllers ---------------------------------------
# Allows to send individual ROS msg of Float64 to each joint separately
blade_1_position_controller:
   type: position_controllers/JointPositionController
   joint: blade_1_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}
blade_2_position_controller:
   type: position_controllers/JointPositionController
   joint: blade_2_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}
main_shaft_position_controller:
   type: position_controllers/JointPositionController
   joint: main_shaft_joint
   pid: {p: 100.0, i: 0.01, d: 10.0}
main_shaft_effort_controller:
   type: effort_controllers/JointEffortController
   joint: main_shaft_joint

