vawt_1:
  controller:
    # Publish all joint states -----------------------------------
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 30

  # Position Controllers ---------------------------------------
  blade_1_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: blade_1_joint
    pid: {p: 100.0, i: 0.0, d: 1.0}

  blade_2_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: blade_2_joint
    pid: {p: 100.0, i: 0.0, d: 1.0}

  main_shaft_joint_position_controller:
    type: position_controllers/JointPositionController
    joint: main_shaft_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}

  main_shaft_joint_effort_controller:
    type: effort_controllers/JointEffortController
    joint: main_shaft_joint