vawt_1:
  controller:
    # Publish all joint states -----------------------------------
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 30

    position:
      # Position Controllers ---------------------------------------
      blade_1_position_controller:
        type: position_controllers/JointPositionController
        joint: blade_1_joint

      blade_2_position_controller:
        type: position_controllers/JointPositionController
        joint: blade_2_joint

      main_shaft_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: main_shaft_joint