joint_limits:
  blade_1_joint:
    has_position_limits: true
    min_position: -1.0
    max_position: 1
    has_velocity_limits: true
    max_velocity: 6.0
    has_acceleration_limits: false
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 1.0
  blade_2_joint:
    has_position_limits: true
    min_position: -1.0
    max_position: 1
    has_velocity_limits: true
    max_velocity: 2.0
    has_acceleration_limits: true
    max_acceleration: 5.0
    has_jerk_limits: true
    max_jerk: 100.0
    has_effort_limits: true
    max_effort: 1.0