vawt_1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  blade_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: blade_1_joint
    pid: {p: 10.0, i: 0.0, d: 1.0}

  blade_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: blade_2_joint
    pid: {p: 10.0, i: 0.0, d: 1.0}

  main_shaft_position_controller:
    type: effort_controllers/JointEffortController
    joint: main_shaft_joint
    pid: {p: 1.0, i: 1.0, d: 0.0}